// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vilderxyz/todos/db (interfaces: DB)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	db "github.com/vilderxyz/todos/db"
	reflect "reflect"
	time "time"
)

// MockDB is a mock of DB interface
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// CreateOneTodo mocks base method
func (m *MockDB) CreateOneTodo(arg0 db.CreateTodoParams) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOneTodo", arg0)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOneTodo indicates an expected call of CreateOneTodo
func (mr *MockDBMockRecorder) CreateOneTodo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOneTodo", reflect.TypeOf((*MockDB)(nil).CreateOneTodo), arg0)
}

// DeleteOneTodo mocks base method
func (m *MockDB) DeleteOneTodo(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOneTodo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOneTodo indicates an expected call of DeleteOneTodo
func (mr *MockDBMockRecorder) DeleteOneTodo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOneTodo", reflect.TypeOf((*MockDB)(nil).DeleteOneTodo), arg0)
}

// GetAllTodos mocks base method
func (m *MockDB) GetAllTodos() ([]db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTodos")
	ret0, _ := ret[0].([]db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTodos indicates an expected call of GetAllTodos
func (mr *MockDBMockRecorder) GetAllTodos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTodos", reflect.TypeOf((*MockDB)(nil).GetAllTodos))
}

// GetManyTodos mocks base method
func (m *MockDB) GetManyTodos(arg0, arg1 time.Time) ([]db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyTodos", arg0, arg1)
	ret0, _ := ret[0].([]db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyTodos indicates an expected call of GetManyTodos
func (mr *MockDBMockRecorder) GetManyTodos(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyTodos", reflect.TypeOf((*MockDB)(nil).GetManyTodos), arg0, arg1)
}

// GetOneTodoById mocks base method
func (m *MockDB) GetOneTodoById(arg0 int64) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneTodoById", arg0)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneTodoById indicates an expected call of GetOneTodoById
func (mr *MockDBMockRecorder) GetOneTodoById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneTodoById", reflect.TypeOf((*MockDB)(nil).GetOneTodoById), arg0)
}

// UpdateOneTodo mocks base method
func (m *MockDB) UpdateOneTodo(arg0 db.Todo) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOneTodo", arg0)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOneTodo indicates an expected call of UpdateOneTodo
func (mr *MockDBMockRecorder) UpdateOneTodo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOneTodo", reflect.TypeOf((*MockDB)(nil).UpdateOneTodo), arg0)
}
