version: '3.8'
services:
  postgres:
    image: 'postgres:14.2'
    ports: 
      - "8080:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recipes
  todo:
    build: 
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - postgres
    restart: on-failure:5
    environment:
      LISTEN_ADDR: "http://localhost:8090/todos"
      GIN_MODE: release
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: recipes
      SERVER_ADDR: 0.0.0.0:80